### ISSUE TITLE
编码器如何连接电脑收发数据

### ISSUE THREAD

**Issue by Valen-C12** [AirExo/collector#1]
我对硬件不是很熟悉，在组装文档里只看到有编码器的购买链接，而且还失效了。
淘宝识图找到个普地磁编码器，看起来挺像的，但它的接口肯定不是USB，所以想请问
- 能列一下或更新下安装手册里的淘宝链接吗
- encorder如何连接电脑收发数据
- 是否需要一个驱动板做桥接
- 有架构和系统要求么，比如x86/arm64，win/Linux/mac
- 是否有详细文档方便不熟悉硬件的同学复现

谢谢：）

**Comment by Galaxies99** [comment]
https://detail.tmall.com/item.htm?abbucket=14&id=770223525902&ns=1&spm=a21n57.1.item.24.17b2523cUsPvEn&skuId=5277779944635

我们在论文后更新了一个版本，现在的链接是这个，应该过段时间会更新一下整个外骨骼的模块。如果要复现论文的版本，我们这段时间让商家开一个原版本的销售链接。

encoder使用485模块连接电脑读数据，在 ubuntu 20.04 x86 下测试过没问题
